[HAY-01] Create SplashActivity
DiscordTime/Hay pull request #8
Opened 2018-08-03 13:29 UTC by CGSILVA

Create Splash Activity, Router, and Espresso test for Splash UI

2018-08-03 14:08 UTC, haldny requested changes

2018-08-03 14:08 UTC, haldny commented on app/src/main/res/values/styles.xml
>          <!-- Customize your theme here. -->
Please, remove this.

2018-08-03 14:08 UTC, haldny commented on app/src/main/res/values/styles.xml
> +    <style name="SplashTheme" parent="Theme.AppCompat.NoActionBar">
Why we are using two NoActionBar style?

2018-08-03 14:08 UTC, haldny commented on app/src/main/res/values/strings.xml
> +    <!-- Splash screen strings -->
We should follow the same pattern to write strings in this file IMHO: page name + type + name E.g. login_hint_name

2018-08-03 14:08 UTC, haldny commented on app/src/main/res/values/colors.xml
> +    <color name="white">#FFFFFF</color>
Why did we need all of these colors?

2018-08-03 14:08 UTC, haldny commented on app/src/main/res/layout/activity_splash.xml
> +        android:id="@+id/loader_img"
Change to: iv_splash_loader

2018-08-03 14:08 UTC, haldny commented on app/src/main/res/layout/activity_splash.xml
> +        android:id="@+id/loader_text"
Change to: tv_splash_loader

2018-08-03 14:08 UTC, haldny commented on app/src/main/res/layout/activity_login.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
We should use constraint layout.

2018-08-03 14:08 UTC, haldny commented on app/src/main/java/br/com/hay/hay/Splash/SplashPresenter.kt
> +package br.com.hay.hay.Splash
remove the second hay folder

2018-08-03 14:08 UTC, haldny commented on app/src/androidTest/java/br/com/hay/hay/SplashTest.kt
> +        var mLoaderText : String = "How are you ?"
Use test resources.

2018-08-03 14:08 UTC, haldny commented on app/build.gradle
> +    androidTestImplementation 'com.android.support.test.espresso:espresso-contrib:3.0.2'
Do we need really all of these libraries?

2018-08-03 14:31 UTC, CGSILVA commented on app/src/main/res/values/styles.xml
> +    <style name="SplashTheme" parent="Theme.AppCompat.NoActionBar">
To remove action bar from splash

2018-08-03 16:18 UTC, haldny requested changes

2018-08-03 16:18 UTC, haldny commented on app/src/androidTest/java/br/com/hay/splash/SplashTest.kt
> +        onView(withId(R.id.tv_splash_loader)).check(matches(withText(R.string.splash_loader_text)))
Change to: textLoaderRight

2018-08-03 16:18 UTC, haldny commented on app/src/main/res/layout/activity_login.xml
> +    <ScrollView android:id="@+id/login_form" android:layout_width="match_parent"
Could you please use ConstraintLayout for this page?

2018-08-03 16:18 UTC, haldny commented on app/src/main/res/layout/activity_splash.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Use ConstraintLayout

2018-08-03 16:22 UTC, victorrattis commented on app/src/main/java/br/com/hay/splash/SplashActivity.kt
> +        mDelayHandler!!.postDelayed(mRunnable, SPLASH_DELAY)
Please consider changing "!!" to "?." because it is safe and "!!" will throw a nullpointExpcation.

2018-08-03 16:24 UTC, victorrattis commented on app/src/main/java/br/com/hay/splash/SplashPresenter.kt
> +package br.com.hay.splash
Please, consider removing the SplashPresenter because the splash screen will not use MPV.

2018-08-03 16:33 UTC, victorrattis requested changes
Please consider my changes.

2018-08-03 16:33 UTC, victorrattis commented on app/src/main/java/br/com/hay/splash/SplashPresenter.kt
> +class SplashPresenter : SplashContract.Presenter {
Please, consider removing the SplashPresenter because the splash screen will not use MPV.

2018-08-03 16:33 UTC, victorrattis commented on app/src/main/java/br/com/hay/splash/SplashActivity.kt
> +        mDelayHandler!!.postDelayed(mRunnable, SPLASH_DELAY)
Please consider changing "!!" to "?." because it is safe and "!!" will throw a nullpointExpcation.

2018-08-03 16:33 UTC, victorrattis commented on app/src/main/java/br/com/hay/splash/SplashActivity.kt
> +        }
:) In Kotlin, it is null-safe, so consider removing the if and using '?.' instead "!!."

2018-08-03 16:33 UTC, victorrattis commented on app/src/main/java/br/com/hay/splash/SplashContract.kt
> +package br.com.hay.splash
Remove this file.

2018-08-07 17:36 UTC, haldny approved these changes

2018-08-07 17:41 UTC, haldny approved these changes

2018-08-07 20:32 UTC, victorrattis submitted a review, later dismissed

2018-08-07 20:32 UTC, victorrattis commented on app/src/main/AndroidManifest.xml
> +            android:theme="@style/LoginTheme">
Please, you could please add "exported=false".

2018-08-07 20:32 UTC, victorrattis commented on app/src/main/java/br/com/hay/splash/SplashActivity.kt
> +        }
Please consider doing it

2018-08-07 20:32 UTC, victorrattis commented on app/src/main/java/br/com/hay/splash/SplashActivity.kt
> +        mDelayHandler!!.postDelayed(mRunnable, SPLASH_DELAY)
Please consider doing it

2018-08-07 20:32 UTC, victorrattis commented on app/src/main/java/br/com/hay/splash/SplashActivity.kt
> +                    goNext(SplashScreen, SplashScreenFinishCount)
Please, could you consider moving the router to the presenter?

2018-08-09 22:16 UTC, merged

2018-08-14 16:17 UTC, haldny reviewed
approved.